xcopy /Y/S ..\..\djondb_0.34\db\buildx64\bson\RelWithDebInfo\djon-bson.lib native\libs\x64
xcopy /Y/S ..\..\djondb_0.34\db\buildx64\cache\RelWithDebInfo\djon-cache.lib native\libs\x64
xcopy /Y/S ..\..\djondb_0.34\db\buildx64\driverbase\RelWithDebInfo\djon-client.lib native\libs\x64
xcopy /Y/S ..\..\djondb_0.34\db\buildx64\driverbase\RelWithDebInfo\djon-clientStatic.lib native\libs\x64
xcopy /Y/S ..\..\djondb_0.34\db\buildx64\command\RelWithDebInfo\djon-command.lib native\libs\x64
xcopy /Y/S ..\..\djondb_0.34\db\buildx64\db\RelWithDebInfo\djon-db.lib native\libs\x64
xcopy /Y/S ..\..\djondb_0.34\db\buildx64\filesystem\RelWithDebInfo\djon-filesystem.lib native\libs\x64
xcopy /Y/S ..\..\djondb_0.34\db\buildx64\network\RelWithDebInfo\djon-network.lib native\libs\x64
xcopy /Y/S ..\..\djondb_0.34\db\buildx64\service\RelWithDebInfo\djon-service.lib native\libs\x64
xcopy /Y/S ..\..\djondb_0.34\db\buildx64\tx\RelWithDebInfo\djon-tx.lib native\libs\x64
xcopy /Y/S ..\..\djondb_0.34\db\buildx64\util\RelWithDebInfo\djon-util.lib native\libs\x64

xcopy /Y/S ..\..\djondb_0.34\db\buildWin32\bson\RelWithDebInfo\djon-bson.lib native\libs\x32
xcopy /Y/S ..\..\djondb_0.34\db\buildWin32\cache\RelWithDebInfo\djon-cache.lib native\libs\x32
xcopy /Y/S ..\..\djondb_0.34\db\buildWin32\driverbase\RelWithDebInfo\djon-client.lib native\libs\x32
xcopy /Y/S ..\..\djondb_0.34\db\buildWin32\driverbase\RelWithDebInfo\djon-clientStatic.lib native\libs\x32
xcopy /Y/S ..\..\djondb_0.34\db\buildWin32\command\RelWithDebInfo\djon-command.lib native\libs\x32
xcopy /Y/S ..\..\djondb_0.34\db\buildWin32\db\RelWithDebInfo\djon-db.lib native\libs\x32
xcopy /Y/S ..\..\djondb_0.34\db\buildWin32\filesystem\RelWithDebInfo\djon-filesystem.lib native\libs\x32
xcopy /Y/S ..\..\djondb_0.34\db\buildWin32\network\RelWithDebInfo\djon-network.lib native\libs\x32
xcopy /Y/S ..\..\djondb_0.34\db\buildWin32\service\RelWithDebInfo\djon-service.lib native\libs\x32
xcopy /Y/S ..\..\djondb_0.34\db\buildWin32\tx\RelWithDebInfo\djon-tx.lib native\libs\x32
xcopy /Y/S ..\..\djondb_0.34\db\buildWin32\util\RelWithDebInfo\djon-util.lib native\libs\x32
