/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package djondb;

public class djonwrapper implements djonwrapperConstants {
  public static FILTER_OPERATORS parseFilterOperator(String text) {
    return FILTER_OPERATORS.swigToEnum(djonwrapperJNI.parseFilterOperator(text));
  }

  public static SWIGTYPE_p_std__setT_std__string_t bson_splitSelect(String select) {
    return new SWIGTYPE_p_std__setT_std__string_t(djonwrapperJNI.bson_splitSelect(select), true);
  }

  public static String bson_subselect(String select, String elment) {
    return djonwrapperJNI.bson_subselect(select, elment);
  }

  public static SWIGTYPE_p_void convert(SWIGTYPE_p_BSONTYPE fromType, SWIGTYPE_p_BSONTYPE toType, SWIGTYPE_p_void value) {
    long cPtr = djonwrapperJNI.convert(SWIGTYPE_p_BSONTYPE.getCPtr(fromType), SWIGTYPE_p_BSONTYPE.getCPtr(toType), SWIGTYPE_p_void.getCPtr(value));
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public static boolean isDaemon() {
    return djonwrapperJNI.isDaemon();
  }

  public static void setDaemon(boolean daemon) {
    djonwrapperJNI.setDaemon(daemon);
  }

  public static void logInfo(String text) {
    djonwrapperJNI.logInfo(text);
  }

  public static boolean endsWith(String text, String end) {
    return djonwrapperJNI.endsWith(text, end);
  }

  public static SWIGTYPE_p_std__string uuid() {
    long cPtr = djonwrapperJNI.uuid();
    return (cPtr == 0) ? null : new SWIGTYPE_p_std__string(cPtr, false);
  }

  public static boolean makedir(String path) {
    return djonwrapperJNI.makedir(path);
  }

  public static SWIGTYPE_p_std__string getHomeDir() {
    long cPtr = djonwrapperJNI.getHomeDir();
    return (cPtr == 0) ? null : new SWIGTYPE_p_std__string(cPtr, false);
  }

  public static String getTempDir() {
    return djonwrapperJNI.getTempDir();
  }

  public static String getCurrentUsername() {
    return djonwrapperJNI.getCurrentUsername();
  }

  public static SWIGTYPE_p_Version getCurrentVersion() {
    return new SWIGTYPE_p_Version(djonwrapperJNI.getCurrentVersion(), true);
  }

  public static SWIGTYPE_p_Version getVersion(String version) {
    return new SWIGTYPE_p_Version(djonwrapperJNI.getVersion(version), true);
  }

  public static int shutdownGracefully(int code) {
    return djonwrapperJNI.shutdownGracefully(code);
  }

  public static void registerShutdownCallback(SWIGTYPE_p_f_void__int callback) {
    djonwrapperJNI.registerShutdownCallback(SWIGTYPE_p_f_void__int.getCPtr(callback));
  }

  public static int clock_gettime(int X, SWIGTYPE_p_timespec tv) {
    return djonwrapperJNI.clock_gettime(X, SWIGTYPE_p_timespec.getCPtr(tv));
  }

  public static SWIGTYPE_p_void mmalloc(long size) {
    long cPtr = djonwrapperJNI.mmalloc(size);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

}
