/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package djondb;

public class DjondbException extends java.lang.RuntimeException {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected DjondbException(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DjondbException obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        djonwrapperJNI.delete_DjondbException(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public String getMessage() {
     String w = what();
     System.out.println("GetMessage: " + w);
    return errorCode() + " - " + what();
  }

  public DjondbException(int code, String error) {
    this(djonwrapperJNI.new_DjondbException__SWIG_0(code, error), true);
  }

  public DjondbException(DjondbException orig) {
    this(djonwrapperJNI.new_DjondbException__SWIG_1(DjondbException.getCPtr(orig), orig), true);
  }

  public String what() {
    return djonwrapperJNI.DjondbException_what(swigCPtr, this);
  }

  public int errorCode() {
    return djonwrapperJNI.DjondbException_errorCode(swigCPtr, this);
  }

}
