/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package djondb;

public class DjondbCursor {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected DjondbCursor(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DjondbCursor obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        djonwrapperJNI.delete_DjondbCursor(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public DjondbCursor(SWIGTYPE_p_BNetworkOutputStream nos, SWIGTYPE_p_BNetworkInputStream nis, SWIGTYPE_p_CommandWriter writer, String cursorId, BSONArrayObj firstPage) {
    this(djonwrapperJNI.new_DjondbCursor__SWIG_0(SWIGTYPE_p_BNetworkOutputStream.getCPtr(nos), SWIGTYPE_p_BNetworkInputStream.getCPtr(nis), SWIGTYPE_p_CommandWriter.getCPtr(writer), cursorId, BSONArrayObj.getCPtr(firstPage), firstPage), true);
  }

  public DjondbCursor(DjondbCursor orig) {
    this(djonwrapperJNI.new_DjondbCursor__SWIG_1(DjondbCursor.getCPtr(orig), orig), true);
  }

  public boolean next() {
    return djonwrapperJNI.DjondbCursor_next(swigCPtr, this);
  }

  public boolean previous() {
    return djonwrapperJNI.DjondbCursor_previous(swigCPtr, this);
  }

  public BSONObj current() {
    long cPtr = djonwrapperJNI.DjondbCursor_current(swigCPtr, this);
    return (cPtr == 0) ? null : new BSONObj(cPtr, false);
  }

  public int length() {
    return djonwrapperJNI.DjondbCursor_length(swigCPtr, this);
  }

  public void releaseCursor() {
    djonwrapperJNI.DjondbCursor_releaseCursor(swigCPtr, this);
  }

  public void seek(int position) {
    djonwrapperJNI.DjondbCursor_seek(swigCPtr, this, position);
  }

}
