/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package djondb;

public class djonwrapper implements djonwrapperConstants {
  public static FILTER_OPERATORS parseFilterOperator(String text) {
    return FILTER_OPERATORS.swigToEnum(djonwrapperJNI.parseFilterOperator(text));
  }

  public static SWIGTYPE_p_std__setT_std__string_t bson_splitSelect(String select) {
    return new SWIGTYPE_p_std__setT_std__string_t(djonwrapperJNI.bson_splitSelect(select), true);
  }

  public static String bson_subselect(String select, String elment) {
    return djonwrapperJNI.bson_subselect(select, elment);
  }

  public static SWIGTYPE_p_void convert(SWIGTYPE_p_BSONTYPE fromType, SWIGTYPE_p_BSONTYPE toType, SWIGTYPE_p_void value) {
    long cPtr = djonwrapperJNI.convert(SWIGTYPE_p_BSONTYPE.getCPtr(fromType), SWIGTYPE_p_BSONTYPE.getCPtr(toType), SWIGTYPE_p_void.getCPtr(value));
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

}
