/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package djondb;

public class ParseException extends java.lang.RuntimeException {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ParseException(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ParseException obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        djonwrapperJNI.delete_ParseException(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public String getMessage2() {
     String w =  djonwrapperJNI.ParseException_what(swigCPtr, this);
     System.out.println("GetMessage: " + w);
    return errorCode() + " - " + what();
  }

  public ParseException(int code, String error) {
    this(djonwrapperJNI.new_ParseException__SWIG_0(code, error), true);
  }

  public ParseException(ParseException orig) {
    this(djonwrapperJNI.new_ParseException__SWIG_1(ParseException.getCPtr(orig), orig), true);
  }

  public String what() {
    return djonwrapperJNI.ParseException_what(swigCPtr, this);
  }

  public int errorCode() {
    return djonwrapperJNI.ParseException_errorCode(swigCPtr, this);
  }

}
