/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package djondb;

public class SWIGTYPE_p_NetworkOutputStream {
  private long swigCPtr;

  protected SWIGTYPE_p_NetworkOutputStream(long cPtr, boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_NetworkOutputStream() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_NetworkOutputStream obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

